[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "twisted-trial-editable"
description = "Twisted Trial issue with editable installs"
version = "0.0.1"

dependencies = ['twisted==24.11.0']
